### ISSUE TITLE
Update npm package/registry

### ISSUE THREAD

**Issue by andresgarza** [ParsePlatform/parse-dashboard#102]
The package in npm's registry is still 0.0.1.

**Comment by drew-gross** [comment]
We are still discussing how we want to manage versions and distribution in the Dashboard. Unlike Parse Server, there should never really be a reason not to be on `master`, and we'd like to avoid a scenario where lots of people are missing out on useful features because they haven't upgraded. Happy to hear the communities input on this one!

**Comment by andresgarza** [comment]
I agree we should always be on master. That said, we are either going to have to `git pull` the latest changes or update the npm package. 

Also, while in the perfect world `master` is always stable, there's bound a time when it breaks this or that feature. In these scenarios, I find npm's versioning way easier than rolling back to a particular commit.

If using npm, docs could even suggest to usethe  Git URL as a dependency instead of using a specific version in the registry.

**Comment by peterdotjs** [comment]
I think @andresgarza does make a good point with stability. Even if we choose not to use `npm` we should add release tags for good points to roll back to if there are any issues.

**Comment by drew-gross** [comment]
This is done now. Check the readme for details.
