### ISSUE TITLE
Cannot install on elastic beanstalk as dependency of parse server

### ISSUE THREAD

**Issue by aryelevin** [ParsePlatform/parse-dashboard#134]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [V] You're running version >=2.1.4 of Parse Server.

- [V] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
I've added "parse-dashboard": "ParsePlatform/parse-dashboard" in dependencies, but after deploy finished, i get the following files in the root of the module:
bin
LICENSE
node_modules
package.json
Parse-Dashboard
README.md

Thats all, where is the lib etc?

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
You will need to clone the dashboard using the instructions in the readme, and then build it (also using the instructions in the readme). It's not set up to be installed via npm yet, although we are working on that.

**Comment by polo2244** [comment]
Hello, is it now possible to do so ?
It isn't woking for me either.

**Comment by flovilmart** [comment]
What is not working? Open a new issue with relevant infos please

**Comment by polo2244** [comment]
I am sorry for being unclear; the title of this closed issue states,
"Cannot install on elastic beanstalk as dependency of parse server"

I was wondering whether it is now possible to implement parse-dashboard as a dependency 
in the server and have it automatically available when the server runs without deploying in node_modules before uploading to aws beanstalk.

I refrained from opening a new issue since this might not be an issue after all.

**Comment by flovilmart** [comment]
Both are just express app. You need to mount them on an express server and deploy to EB
