### ISSUE TITLE
Solution to Heroku building/running fail

### ISSUE THREAD

**Issue by didierfranc** [ParsePlatform/parse-dashboard#221]
Building heroku app from this repo fails every times for me, bundle.js could be missing so I solve that but there is possibly RAM problem with small dyno or anything else during installation ...

So I made this on top of the **latest npm version**, it makes it easier and faster to deploy :

https://github.com/didierfranc/parse-dashboard-heroku

And the same way with Parse-server :

https://github.com/didierfranc/parse-server-heroku

This way we'll avoid a lot of problems :+1:

**Comment by drew-gross** [comment]
Thanks for the help! Since this isn't an issue but rather a community link, I'm going to close it. Also, I noticed you've enabled the insecure HTTP option so as a warning to anyone planning to use that repo, I want to say that you need to ensure that your dashboard is accessible over HTTPS only or you will be in severe danger of leaking your Master Key.

**Comment by philohelp** [comment]
@didierfranc fantastic thanks ! I can access the dashboard main menu easily but then I get a "Server not reachable: server version too low" (server was installed with the Heroku button). Should I fork the server-example and then deploy it on Heroku or is there a more simple workaround ?

**Comment by didierfranc** [comment]
I advice you to use both https://github.com/didierfranc/parse-server-heroku and https://github.com/didierfranc/parse-dashboard-heroku

You will deploy the latest version of each.
