### ISSUE TITLE
Parse Import Function Disappeared

### ISSUE THREAD

**Issue by smooret2k** [ParsePlatform/parse-dashboard#336]
The Parse import function is no longer present on the dashboard.

**Comment by stretchnz** [comment]
I also have this issue - as do others judging on stack overflow boards.
Can we get an official word on why this may be?

**Comment by pascalgiguere** [comment]
Same issue here. Weird that they'd discontinue this feature without any warning.

If anybody has a workaround, I'd be interested. I am trying to import thousands of objects from a JSON file.

**Comment by takiwax** [comment]
Same here.  I really need this function to replace data with exact same objectId.

**Comment by pascalgiguere** [comment]
I was going to write a custom node script that uses Parse's REST API to replicate the import feature, but then I realized it doesn't seem possible given that you cannot manually set the objectId when creating new objects... This is problematic in my case so I hope the feature is coming back soon.

**Comment by powhu** [comment]
> As you might have heard, Parse will be shutting down in January next year and we encourager every developer to migrate their database off Parse and eventually setup their own Parse Server (which is now Open Source).

https://developers.facebook.com/bugs/1299703926710381/

I asked this question on FB Developer support. They say they won't fix......

**Comment by pascalgiguere** [comment]
I made a node.js script that allowed me to replicate Parse's import feature. It worked for my specific use case, but you probably will want to adapt it depending on your needs.

What this allowed me to accomplish was:

1. Export JSON backup of a Parse class using Parse's export feature.
2. Drop entire Parse class using Parse's dashboard.
3. Re-import data from the exported JSON file back into Parse using this script.
4. The imported data will have **different objectIds** compared to the backup. The script will however take care up updating pointers of another Parse class so that pointer relations don't break despite the objectId change.

https://gist.github.com/pascalgiguere/6978c87a2e9a63ddf7577ddaf1b32f3c
Use at your own risk and feel free to improve / adapt for other use cases!

**Comment by drew-gross** [comment]
> https://developers.facebook.com/bugs/1299703926710381/

> I asked this question on FB Developer support. They say they won't fix......

Looks like this has been answered by Facebook. You should migrate your database, then import directly to mongo.

**Comment by KapoorKarn** [comment]
All, take a look at mongochef (http://3t.io/mongochef/), i've been using it since the removed the bulk import function from the dashboard.  Mongochef has allowed me to easily add/remove/modify classes.
I've been able to import semi large csv's to my dbs (roughly 10k records).  For large csv files i've been doing a bulk import.  There is a commercial and non-commercial option available.  

I know some other have mentioned some ways to import as well, but i'm not very skilled in scripts, shells, or yadda yadda.  Anyway, just wanted to post in case it helped someone.

**Comment by Treverr** [comment]
Im a but confused as to why we are told "import directly using MongDB" when you can't do that and parse be able to use/see the files......?

**Comment by stretchnz** [comment]
I have long given up on parse.com hosting.
We are using NodeChef which has a Parse hosted Dashboard.
It also allows direct import via CSV / JSON etc, very very nice for what we need.

**Comment by Treverr** [comment]
We are hosting it all ourselves and are in a situation where we need to import the data. But alas this vital piece was left out.

**Comment by stretchnz** [comment]
hmm cant help there then sorry, was not prepared to entertain the idea of hosting ourselves.

**Comment by flovilmart** [comment]
It sure what you mean by import the data, you can use mongo to import existing tables, or the SDK's to write the data in à Parse specific format.
