### ISSUE TITLE
Show an error message when the iconsFolder can't be found

### ISSUE THREAD

**Issue by drew-gross** [ParsePlatform/parse-dashboard#359]
In #358 the icons folder appeared to be missing, and @deada92 was unable to debug because there were no error messages. We should `console.log` an error message that shows where we tried to load the icons from if that folder doesn't exist.

**Comment by deada92** [comment]
Can you hint me to the right direction? I would love to contribute and fix this..

**Comment by drew-gross** [comment]
Awesome! The place where we server the icons is here: https://github.com/ParsePlatform/parse-dashboard/blob/master/Parse-Dashboard/app.js#L118

You'll probably just want to check if the folder exists somewhere, and if it doesn't then print out the path where we tried to access it. If you want to be extra fancy, you could also check the the actual icon files specified in the app's info exist as well, but that would be tricker.

**Comment by deada92** [comment]
Hello @drew-gross ,

it seems like the problem is somewhere else or I'm not able to see the issue. My current branch is having the same problem when I run it locally: https://github.com/deada92/parse-dashboard/tree/icon-folder-check

what I have tried so far: 
1. checking if the directory exist
2. serve the path of the directory with the config variable and also hardcoded it once to check if its a variable problem.

It seems like serving the path with `app.use('/appicons, ...);` is not working correctly..

**Comment by drew-gross** [comment]
No, the image should be able to be any format, the dashboard just serves the file and leaves it up to the browser to interpret the file. Once you hard-code the path, can you load the image just by entering the URL in your browser?

**Comment by deada92** [comment]
No that's the problem. I even printed the directory path as you see in my branche and it shows the right path. I get always 404. 

It's crazy because I can't see anything breaking things up. Any idea where I can continue searching? I traced all the way to AppIndex.react.js. Unfortunately I'm not that familiar with react.

**Comment by drew-gross** [comment]
My tactic when I see a crazy issue like that is to create a new project that just does the thing I want to do, make it work, and then move the code into the real project.

**Comment by deada92** [comment]
That's exactly what I did with cloning this repo and editing directly the source. The only difference is my config file. Does this really works on your end?

**Comment by drew-gross** [comment]
Yep it's working for me: 

![image](https://cloud.githubusercontent.com/assets/558242/15445641/c3c769e8-1eb7-11e6-8523-2918f53986e2.png)

**Comment by deada92** [comment]
shame on me.. I always forget the callbacks structure when I work with js.. I'm displaying now just info logs if something is wrong. Is there a way to display the user a error message on the dashboard?

**Comment by deada92** [comment]
i think this can be closed ;)
