### ISSUE TITLE
build failing with node-sass@3.3.3

### ISSUE THREAD

**Issue by kilabyte** [ParsePlatform/parse-dashboard#47]
We have latest Node.js yet we can't get it to build. We also have the latest version of parse-server up and running so all dependancies should be met? Somewhere else in the log it mentioned that our OS is not supported? How can it be that we can run parse-server with no problems and can't install the dashboard because the OS isn't supported?

![screen shot 2016-03-04 at 7 14 24 pm](https://cloud.githubusercontent.com/assets/487948/13545349/59341dda-e23d-11e5-96b3-c6a22fa75967.png)

**Comment by drew-gross** [comment]
What OS are you using? The npm package documentation for `node-sass` mentions some issues on Ubuntu https://www.npmjs.com/package/node-sass could you follow those instructions and let me know if they help? I've also updated the `node-sass` version to the latest in #49 which may help.

**Comment by kilabyte** [comment]
Running on CentOS 6. I'll try #49 and report back

**Comment by kilabyte** [comment]
checkout node-sass-version and got everything up and running on my server and i can access it now!

**Comment by drew-gross** [comment]
Great! Https is required because the dashboard transmits your master key over the network. If you want to turn that off you can dig into the source of `Parse-Dashboard/index.js`, but be careful not to use the master key for apps that are important to you (or make sure you have some other security mechanism, such as early SSL termination)

I'd also accept a PR that makes this process easier, so that the people who know what they are doing can deploy the dashboard without the https requirement.
