### ISSUE TITLE
Deleted entire database

### ISSUE THREAD

**Issue by louisecroft** [ParsePlatform/parse-dashboard#580]
Hi,

I tried to delete one row in our database but instead deleted all 6000 users - at around 9pm EST on 8th November. (#epicfail I know). We know there is no 'undo' or official backups but we're hoping there might be a partial backup somewhere else on your servers.

We've since managed to recover most of the users (we had a six month old backup ourselves) but have still lost 300, and some of their settings. 

I'm not sure what kind of access is most helpful but this is our account: https://www.parse.com/apps/journorequest

If you guys can help it'd be massively appreciated!

All the best,
Louise

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.18 of Parse Dashboard.

- [x] You're running version >=2.2.18 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by steven-supersolid** [comment]
Hi Louise, this project is for the open-source self-hosted parse dashboard and it looks like you deleted data on parse.com. I'm sorry but no-one here has access to or can offer support for the dashboard on parse.com. Your only chance is to contact Parse support from the 'contact us' link on the page http://parse.com/help

I recommend you migrate your database off parse.com as soon as possible due to it being shut down soon. Services such as mlab and MongoDB Atlas offer automatic backups so you don't have to worry as much about things like this happening in future.

**Comment by lacker** [comment]
Chatted with Louise a bit, but yeah you should file a ticket at parse.com/help .
