### ISSUE TITLE
How do I set up 'settings' menu in dashboard on server initialisation? 

### ISSUE THREAD

**Issue by BillyJohn3** [ParsePlatform/parse-dashboard#684]
I am told the only way to get the settings menu in the Parse server dashboard is to do so during server initialisation but can't find out how to do it. 
Can anyone offer any help on how to do so?

Cheers,
Simon

**Comment by natanrolnik** [comment]
Simon, what I meant by "server initialization" was not referring to the dashboard. The dashboard **does not** have settings anymore. Instead of using the dashboard's UI to change settings like push, one configures push and other options when the Parse Server itself is initialized. 

Did you read the server docs?
