### ISSUE TITLE
Manage CLPs with Dashboard

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-dashboard#72]
Will it eventually be possible to manage Class Level Permissions in the new dashboard like we were able to previously on the hosted dashboard? This would be a very useful feature. Also great job on this, looks great!

**Comment by greggmojica** [comment]
+1

**Comment by peterdotjs** [comment]
@dcdspace we are missing some endpoints that we had in Parse.com to support CLPs. If you or anyone is interesting in creating a PR we'll gladly point you guys in the right direction.

**Comment by dcdspace** [comment]
@peterdotjs yes please that would be appreciated. Is it as simple as interacting with the SCHEMA collection in the database or is there more to it?

**Comment by flovilmart** [comment]
@peterdotjs can you put a GIST with the spec for that API?

**Comment by drew-gross** [comment]
@flovilmart @dcdspace actually the original CLPs endpoint went through parse.com/apps instead of api.parse.com so there is no spec. We'll need to come up with a new API for this one. I think it would be nice to put it into the Schemas API, but I'd be glad to hear other ideas :). If schemas API is what we want to go with, the files you will need to modify to create the endpoint are in Parse Server: [Schema.js](https://github.com/ParsePlatform/parse-server/blob/master/src/Schema.js) and [SchemasRouter.js](https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/SchemasRouter.js), with tests in [Schemas.spec.js](https://github.com/ParsePlatform/parse-server/blob/master/spec/Schema.spec.js) and [schemas.spec.js](https://github.com/ParsePlatform/parse-server/blob/master/spec/schemas.spec.js). Actually retrieving the data to put in the endpoint is as simple as looking at the _SCHEMA collection.

You will also need to update the Parse Dashboard to understand this new format in [the permissions dialog](https://github.com/ParsePlatform/parse-dashboard/tree/master/src/components/PermissionsDialog). Since Parse Server doesn't understand pointer permission yet, you'll also need to disable Pointer Permissions with a flag in the editor.

This is not a small job! I'd be quite happy to work closely with you on this if you are excited about contributing :)

**Comment by jcguarinpenaranda** [comment]
+1

**Comment by flovilmart** [comment]
The API is merged and mounted on the schema endpoint

**Comment by dave4506** [comment]
+1

**Comment by jasonjasonjasonjason** [comment]
+1

**Comment by davimacedo** [comment]
+1

**Comment by drew-gross** [comment]
Now that Parse Server has the necessary endpoints, I'm working on getting this set up in Parse Dashboard.

**Comment by zh-wowtv** [comment]
Is this implemented already? How to use it? Thanks.

**Comment by jherrmann** [comment]
Hi,
from #175 it sounds like that there should be a CLP editor in the Dashboard. But I cant find it anywhere. I would greatly appreciate it if someone could tell me how it should work. Thx
